### ISSUE TITLE
LOS_calc_signal computation of quadrature rules optimization

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#142]
When computing quadrature rules, for some with do it in two steps: the first one to compute the total size of quadrature points and the second one, after the creation of the arrays, fills the latter with the computed values.
For others with do these two steps in one loop and realloc the arrays at each step.

It might be quicker to do this always in two steps and thus be able to parallelize both loops.

**Comment by Didou09** [comment]
Fixed, in deve, by PR #164

**Comment by Didou09** [comment]
Closed in 1.4.1
