### ISSUE TITLE
MinMax not used when computing Surface sampling

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#180]
In ``tofu/geom/_comp.py`` in the function ``_Ves_get_sampleS`` four parameters are taken and never used: ``Min1, Max1, Min2, Max2``. They are transformed to two list, see:

https://github.com/ToFuProject/tofu/blob/a5c8cf8d43b8a43b73bee8f6688d6a1b74ea2979/tofu/geom/_comp.py#L287-L288

But, when calling core function for sampling they are never used. Since there is no doc, not sure what are this parameters ? Are they the limits for `Phi` ?

**Comment by lasofivec** [comment]
After discussing with @Didou09 these variables look useless, taking them out in new branch...

**Comment by Didou09** [comment]
Fixed, in devel, by PR #181
