### ISSUE TITLE
Mac OSX - OpenMP - reduction

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#183]
After much consideration, I am opening an issue here even though it is **not** a **tofu** error but a problem of configuration between OSX, Cython an OpenMP, which leads to **wrong** results (tests failing) even if there is no issue in **tofu** and no warning/error displayed.

The first issue I found is that with ``homebrew``'s ``gcc-8``, OpenMP reductions are not being run in parallel but repeated. 
Some example can be found here:

https://stackoverflow.com/questions/54776301/cython-prange-is-repeating-not-parallelizing
https://github.com/bearnshaw/mult-cython
https://github.com/cython/cython/issues/2316

**Comment by lasofivec** [comment]
The solution seems to be to use ``conda``'s ``gcc`` and make sure this is the one being used by default, ie. ``which gcc`` should give something among the lines:
``/Users/<username>/anaconda3/envs/<yourenv>/bin/gcc``.

Since **tofu** used to fix the ``gcc`` compiler only for the compatibility with OSX, the ``setup.py`` can be updated so that it doesn't anymore. I will add the specification for the ``gcc`` compiler to the documentation.
This will also simplify the installation on ITER as Simon Pinches has to do a patch currently for the installation.

**Comment by Didou09** [comment]
Fixed, in devel, by PR #184
