### ISSUE TITLE
In _core.py: unused variable

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#186]
https://github.com/ToFuProject/tofu/blob/807da74401e4e96f849127e7dae8afcd558f9dc0/tofu/geom/_core.py#L423-L425

The variable here is declared but not used

**Comment by lasofivec** [comment]
I can erase this variable (and thus also `Typesu` which is only needed for `lc` declaration.
@Didou09  can you confirm it? If so, I can do it

**Comment by Didou09** [comment]
Not sure, I need to think about it, it might be that there is typo on the line below and that it should be saying something like :
``` assert np.all(np.any(Typesu, axis=0)) ```

In which case lc and Typesu are necessary,
Give me one day more

**Comment by lasofivec** [comment]
Since `Typesu` is the same as `Types` but after `np.unique` seems to me that both statements are equivalent.
Meaning `assert np.all(np.any(Typesu, axis=0))` is equivalent to `assert np.all(np.any(Types, axis=0))`, and the second one should be more general.
