### ISSUE TITLE
Two init functions for CoilPF

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#187]
In `_core.py` there are two different initializers for `CoilPF` class:

https://github.com/ToFuProject/tofu/blob/807da74401e4e96f849127e7dae8afcd558f9dc0/tofu/geom/_core.py#L1503-L1518

**Comment by lasofivec** [comment]
It seems to me like we can keep the second one. @Didou09 if you confirm I can solve this issue

**Comment by Didou09** [comment]
Thanks for the info, I'll look tomorrow morning also, not sure immediately
