### ISSUE TITLE
Tools for CamLOS closest points

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#211]
Create two methods with easy / explicit names in Rays:
* one to compute the geometrically closest point of each LOS to an axis (using self.set_dsino() and returning only the distance, theta and pts
* one to compute the points of minimum rho from a Plasma2D instance and returning rho, theta and the pts

**Comment by Didou09** [comment]
Fixed in devel by PR #212

**Comment by lasofivec** [comment]
> Create two methods with easy / explicit names in Rays:
> 
>     * one to compute the geometrically closest point of each LOS to an axis (using self.set_dsino() and returning only the distance, theta and pts


What do you mean by axis?
In any case if an axis is a line, then there is already a function that is similar to this probably.

**Comment by Didou09** [comment]
Yes, the functions in _GG are all already existing and operational, I just added extra methods to the Rays class with more explicit names from a tokamak point of view (axis = magnetic axis = circle in 3d)

Fixed
