### ISSUE TITLE
Integrate ITER new config

### ISSUE THREAD

**Issue by munechika-koyo** [ToFuProject/tofu#220]
I have extracted a more accurate configuration for ITER using CAD data, as can be seen below:
![ITERConfig](https://user-images.githubusercontent.com/51052381/67562208-9147eb80-f71e-11e9-8b22-48b0999bb4dd.png)

It would be nice to make it available in tofu for other users

**Comment by lasofivec** [comment]
Dear @munechika-koyo,
That looks amazing. It looks like you are ready to do your first pull-request !
Did you created your own branch or did you fork the project?
I am going to add the instructions on how to create a pull request :)

**Comment by munechika-koyo** [comment]
> Dear @munechika-koyo,
> That looks amazing. It looks like you are ready to do your first pull-request !
> Did you created your own branch or did you fork the project?
> I am going to add the instructions on how to create a pull request :)

Yes! I already create my own branch named "Issue220_NewITERConfig".
Also, Didier told me how to create a pull request, so that would be fine :)

**Comment by Didou09** [comment]
Thanks Koyo for this nice addition to tofu,
Laura, if you can still add some instructions on for doing the pull request I feel it is still a very good ideas, both as a reminder of good practices and for newcomers.
In particular to make sure contributors do the pull request to devel and not to master directly, at least.
Many thanks !

**Comment by lasofivec** [comment]
Done, documentation is up to date.
