### ISSUE TITLE
Support of python 3.7

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#23]
I was trying to configure Travis tests with Python version 3.7, after some configurations, I just realized there is a bottom line:

> conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
>   - polygon3 -> python[version='>=3.6,<3.7.0a0']
>   - python=3.7

So we either try to move forward without the polygon library or we drop the support of python 3.7 (knowing that for the future this still will have to be solved)

**Comment by Didou09** [comment]
I think we will move on without Polygon,
It is used for your next main task, to compute polygon intersections and polygon surfaces and barycenters, but you have already started writing a substitute for it.

I think tofu will be more self-contained and faster without it.
This should auto-resolve in the coming months, so let's just postpone support to Python 3.7 till then.

**Comment by Didou09** [comment]
Closed in 1.4.1
