### ISSUE TITLE
Stop Python 2.7 support

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#230]
From the next version, tofu will not support python 2.7 anymore
This means we can remove the python 2.7 builds in travis.yml

**Comment by lasofivec** [comment]
There's already a branch with this in mind see SHA: 7e321f6c3d49303ecd05cbbc8ef471934e970c81

**Comment by Didou09** [comment]
Ok, but please next time open a dedicated issue and name the branch accordingly, it easier to follow.
Do you want to consider this issue as being associated to the branch you mention then ?

**Comment by lasofivec** [comment]
done

**Comment by Didou09** [comment]
Just to preserve the workflow:
* issue labelled "fixed in devel" when the PR accepted
* issue closed only when solved in the last release or when it was opened by mistake (e.g.: the bug does not really exist...)

This way we'll easily get a list of all additions to a release simply by collecting all issues labelled "fixed in devel", and we'll close them all after the release is done

=> I re-open the issue and label it "fixed in devel", to keep track as a good practice
