### ISSUE TITLE
Moving on from nosetests...

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#232]
As seen in `Nose` documentation:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

We should choose a new tool and move on from `nose` before it's too late ;)

**Comment by Didou09** [comment]
Keep in mind Issue #216

**Comment by lasofivec** [comment]
Fixed by #445
