### ISSUE TITLE
[CI] conda_build step is taking a long time

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#239]
Since last update of `conda-build`, the time of the building library went up to 18 mins.

**Comment by lasofivec** [comment]
It seems it is coming from https://github.com/conda/conda-build/issues/3775#issue-507970515

**Comment by Didou09** [comment]
good catch, indeed it seems conda-dependent

**Comment by Didou09** [comment]
Closed since PR #249 which removed two nested for loops in tests01_geom/tests03_core.Test03_Rays.calc_signal()
