### ISSUE TITLE
Bug in _GG_LOS_calc_signal()

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#247]
Trying to debug PR #207, I realized the output of the script:
examples/tutorials/plot_custom_emissivity.py

Depends a lot on whether newcalc=True or False

True: (new optimized routines) - wrong result (for example: no negative values, sharp edges...)
![tofu_issue247_newcalcTrue](https://user-images.githubusercontent.com/5929562/68292196-a102f080-008b-11ea-83d6-cce42d7e6031.png)

False: (old reference routine) - good result
![tofu_issue247_newcalcFalse](https://user-images.githubusercontent.com/5929562/68292202-a52f0e00-008b-11ea-91d2-d96c01c30d43.png)

**Comment by Didou09** [comment]
High priority, we shoul probably issue a new released when fixed, as current users may run into false results

**Comment by Didou09** [comment]
Once the bug is identified, solved and similar routines are double-checked, I suggested adding a new unit test based on this particular tutorial to check that the results of newcalc=True and newcalc=False are very close / identical (use np.allclose()), what do you think ?

**Comment by Didou09** [comment]
Fixed in devel by PR #249

**Comment by jdhare** [comment]
Resolved in 1.4.2, many thanks!

**Comment by Didou09** [comment]
Yes :-)
tofu 1.4.2 is currently in pre-release (alpha), we're testing its portability (ease of installation on several platfoms : Linux, Mac OS, Windows via pip, conda and easyconfig).

So a final (non-alpha) release 1.4.2 will come soon, but most of the bugs and new features are already available in the alpha, so don't hesitate to use it already (and to report any new problem by openeing an issue here). Thanks for your support and feeback @jdhare !
