### ISSUE TITLE
Re-format output of user-defined signal function when t=None

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#252]
From #248 and https://github.com/ToFuProject/tofu/pull/207#issuecomment-540046272, I've gathered that the doc for how to define the function of the signal to integrate is not read so when "t=None", there is an error that the user does not understand.
I think it will be easier to check what's being passed when the pre-formatting is done, and use a wrapper so that the function always return a 2D array.

**Comment by Didou09** [comment]
Fixed in devel by PR #254
