### ISSUE TITLE
Check imas version and warn user

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#287]
On the ITER cluster, and on any install where IMAS is loaded via linux environment modules, imas2tofu should check, at import time, the currently loaded imas version against the latest version available.

If a more recent version is available, it should issue a warning message accordingly

**Comment by lasofivec** [comment]
This looks like an IMAS issue to me ?

**Comment by Didou09** [comment]
It is a user-friendly feature that just checks which module was loaded in the user environment against the other modules available (i.e.: module list vs module avail).
I noticed that I tend to pre-load a list of modules on the ITER cluster and only rarely check that they are up-to-date.
I suspect other users do the same.
But the IMAS versions change rapidly, new modules are created quite often with easyconfig, and the user may not be aware that he has loaded an old version of IMAS.

This will warn him :-)

**Comment by Didou09** [comment]
Fixed, in devel, by PR #289

**Comment by lasofivec** [comment]
Do you do `module load <package>=<version>` if you want to always use the latest version you can just `module load <package>`.
I will accept the PR but it seems to me something that tofu shouldn't (have to) handle

**Comment by Didou09** [comment]
I don't do module load, tofu should not load / unload packages.
I just check the already loaded packages (module list vs module avail) and inform the user.

It is done in imas2tofu, a sub-package dedicated to the imas interfacing.
It imas is not present, imas2tofu is not loaded and this is done anyway

**Comment by lasofivec** [comment]
I meant what you do in your `bashrc` I agree this has nothing to do with tofu ;)
