### ISSUE TITLE
Useless files in root directory

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#288]
in tofu's root directory, these files can probably be deleted / moved:

- Debug_JINTRACMesh.pdf
- Debug_JINTRACMesh.svg
- XICS_mask.npz
- TODO_EndOfVisit_20181212.txt

**Comment by Didou09** [comment]
Yes for all, good point
can you do it on devel ?

**Comment by Didou09** [comment]
Rectification, I'm doing it now
