### ISSUE TITLE
Improve general PEP8 compliance

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#30]

**Comment by lasofivec** [comment]
I found out about this project during Euroscipy 2019 and I think we should use it from now on, it takes only a few clicks to make it work:

https://pep8speaks.com/

It checks the modified code for pep8 compliance when doing a PR, you get a message and it doesn't block the PR.

**Comment by Didou09** [comment]
Seems a good idea to me, thanks for it, 
Having a look, and will set up is no issues

**Comment by Didou09** [comment]
@lasofivec , since PR #240  is now merged and closed I label this issue as "fixed in devel", ok for you ?

**Comment by lasofivec** [comment]
it's PR #236 but yes :)
