### ISSUE TITLE
accessing private method in tutorial

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#301]
Normally methods/parameters starting with "_" are private.
However in a tutorial we do:

`tf.geom.utils._DCONFIG_TABLE.keys`

it looks to me like there should be a function

`tf.geom.utils.get_all_configs_key()`

for example.

**Comment by Didou09** [comment]
Yes definitely,

Will do it in the coming days

**Comment by Didou09** [comment]
Fixed, in devel, by PR #327
