### ISSUE TITLE
CamLOS2D being called when creating a 1D cam

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#31]
When creating a 1D cam with only one ray, ie:

> D = [0,0,0]
> u = [0.1, 0.1, 0.1]
> cam = tf.geom.CamLOS1D(Exp="Dummy", Name="Dummy", dgeom=(D, u),
                            config=config, Diag='Test', method="ref", plotdebug=False)

There is an error, and Cam2D is called

**Comment by Didou09** [comment]
Could be linked to issue 51

**Comment by Didou09** [comment]
Solved in devel by PR #134 
Required implementing a test (nRays > 1)

**Comment by Didou09** [comment]
Closed in 1.4.1
