### ISSUE TITLE
tofu pypi build does not ship the configuration files?

### ISSUE THREAD

**Issue by flothesof** [ToFuProject/tofu#386]
Hi,

in the context of the work I'm doing on #382 I've realized what I think is a problem. tofu is supposed, when installed by a user, to ship default configurations of machines, right?
More specifically, the sdist over at pypi (https://files.pythonhosted.org/packages/00/7b/4eb998cec2acf5df56e08a452dd7db194b63300120273a77e9f6179b9e75/tofu-1.4.4.tar.gz) when inspected only contains the deprecated geom files in tofu/geom/inputs:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/2360669/81273251-e6aa7100-904e-11ea-9560-1567f50d79d0.png">
This is one of the reasons the tests of the current conda-forge recipe fail: they are unable to find the configuration files.

After doing some lookup in the source, it seems this was already investigated (and fixed) in #377 .
However, I have one extra question: there's another folder in tofu/geom/inputs called test_data which is not part of the shipped files as far as I can tell. Is this normal?
Could someone please double check this, please?

Regards,
Florian

**Comment by Didou09** [comment]
You're right, the first issue was spotted in #377 and fixed by PR #378 (not ncluded in 1.4.4, will be included in 1.4.5)

The second one however (test_data).... I need to double-check (might take a few days due to workload)

Thanks !

**Comment by flothesof** [comment]
Thanks for your feedback. This is then a duplicate issue. I'm not sure the test_data thing is relevant. Feel free to close the issue.

**Comment by Didou09** [comment]
Double check: test_data was a temporary artefact, specific to a branch that does not exists anymore.

Since the main issue is already fixed in the next release by PR #378, I'm closing the issue
