### ISSUE TITLE
Adding COMPASS geometry

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#400]
The Czech plasma research institute recently made a lot of info available online about their tokamak [COMPASS](http://www.ipp.cas.cz/vedecka_struktura_ufp/tokamak/).
It would be nice get the geometry and add it to the next tofu release.

Do you think you could take care of this @flothesof ?

If so: browse the web pages in search for the most detailed geometry and extract it.
So far I think maybe [here](http://www.ipp.cas.cz/vedecka_struktura_ufp/tokamak/compass_u/) or [here](www.ipp.cas.cz/vedecka_struktura_ufp/tokamak/compass_u/Systems/Magnetic_field_coils.html)

**Comment by flothesof** [comment]
Sure, I'll look into it next week!

Cheers,
Florian

**Comment by flothesof** [comment]
Hi @Didou09,
I've been looking into this and the available information isn't that great, unfortunately.
The best poloidal plane drawing I could find is this one:
![image](https://user-images.githubusercontent.com/2360669/84123092-a701eb00-aa39-11ea-80fe-89fe0c115d21.png)
Taken from the conceptual design paper about Compass-U https://www.sciencedirect.com/science/article/pii/S0920379617302053#fig0030

Do you think the bold structures are enough to model Compass-U in tofu? As you may notice they're not closed, which seems surprising to me.

If you're positive this is enough, I can apply some image analysis and extract the bold surfaces, close them, find the scale and do a PR for tofu.

What do you think?

Cheers
Florian

**Comment by flothesof** [comment]
After further investigation, I think the best illustration is [this one](http://www.ipp.cas.cz/miranda2/export/sitesavcr/ufp/sys/galerie-obrazky/Single_null_double_null.png): 
<img src="http://www.ipp.cas.cz/miranda2/export/sitesavcr/ufp/sys/galerie-obrazky/Single_null_double_null.png" />
I could extract the different geometrical elements out of this structure.

**Comment by flothesof** [comment]
Yet another image, with scale (yay!) [here](http://www.ipp.cas.cz/miranda2/export/sitesavcr/ufp/sys/galerie-obrazky/single_double_conf.png):

<img src="http://www.ipp.cas.cz/miranda2/export/sitesavcr/ufp/sys/galerie-obrazky/single_double_conf.png" />

**Comment by Didou09** [comment]
Yes !
Cool, if you can extract the elements from this scaled sketch, it would be cool!
Also, tofu needs at least one closed surface, maybe you could use this scaled sketch to extract the scaled coordinates of the first figure (of which you would closed the thick light blue elements by linking them together as a single contour, and leave the dark blue and green elements as individual thick elements) ?

**Comment by Didou09** [comment]
Hey @flothesof ,
Any chance you could try extracting a nice geometry for COMPASS ?
The first figure you suggested looks a nice basis, using the scale provided in the last figure.
I'll try to release a new version soon to accelerate conda-forge integration, and it would be nice to include COMPASS in it ;-)
