### ISSUE TITLE
Update README.md / thoughts about improvements

### ISSUE THREAD

**Issue by flothesof** [ToFuProject/tofu#414]
Following the recent integration into conda-forge, I spotted the fact that README.md has outdated instructions for installation.
```
Installing tofu
For Ubuntu
Standard mode
conda install -c tofuproject tofu
```
I think this should be deprecated for conda-forge install instructions instead.

Also, the Readme file says

`A sphinx-generated documentation (to be updated soon)`, 

which I think should be rewritten.

More generally, my feeling is that the README could benefit from a little bit of restructuring (maybe there are too many things in it?).

We could take some inspiration from pyvista's README : https://github.com/pyvista/pyvista

In particular I like the fact that:

- they have a nice visual on top
- a short project description
- a link to the examples with a MyBinder link (we could do that too, so that users can just test run the library from their browser)

We already have some cool visuals but as I said I think we lack a little clarity. So redefining the scope of README.md would probably help, e.g. say what is someone expecting who comes here for the first time, someone who knows about tofu but would like to install it, someone who wants to know what it does...

Cheers,
Florian

**Comment by lasofivec** [comment]
Not sure if all points made by @flothesof were solved by the PR ? Did you discuss privately ?
