### ISSUE TITLE
Error when loading AUG config

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#513]
So I was trying to update the doc when I noticed the following script was failing `examples/tutorials/tuto_plot_gallery_fusion_machines.py` (also in tests). First, there are many 

> /home/lasofivec/tofu/tofu/geom/utils.py:854: UserWarning: Could not be loaded: TFG_PFC_ExpAUG_D2cdome.txt

and it ends with

> 
> Traceback (most recent call last):
>   File "examples/tutorials/tuto_plot_gallery_fusion_machines.py", line 40, in <module>
>     config.plot()
>   File "/home/lasofivec/tofu/tofu/geom/_core.py", line 3777, in plot
>     vis = self.get_visible()
>   File "/home/lasofivec/tofu/tofu/geom/_core.py", line 2891, in <lambda>
>     setattr(self, "get_%s" % pp, lambda pk=pp: self._get_extraprop(pk))
>   File "/home/lasofivec/tofu/tofu/geom/_core.py", line 2806, in _get_extraprop
>     k0, k1 = self._dStruct["lorder"][0].split('_')
> IndexError: list index out of range
> 

The actual error is because no file was read successfully.
 From what my investigation is coming from the following lines

https://github.com/ToFuProject/tofu/blob/f0697ffb2c9afa93ab31f4be31c0d97496303f78/tofu/geom/_core.py#L1968-L1977

AUG is the only configuration for which the data is separated by several white spaces, and as the delimiter is marked as one white space and not as None which NumPy interprets as one or several whitespaces, then the second column is thought to be a white-space and the actual data is ignored.

## Remark
What I haven't understood yet is how this was not caught before nor in the CI. But I will look into it on Monday.
Might be a new version of numpy? 

## Versions
numpy version: 1.20.1
tofu branch: Issue407_StructFromFiles
tofu version: 1.4.10-alpha9-280-g3fdd0810
(I tried with devel as well, same error)

## A possible solution:
https://github.com/ToFuProject/tofu/blob/f0697ffb2c9afa93ab31f4be31c0d97496303f78/tofu/geom/_core.py#L1972
just use `None`

**Comment by Didou09** [comment]
So if we use None it solves the problem?
