### ISSUE TITLE
Removing all structures of config raises Exception

### ISSUE THREAD

**Issue by lasofivec** [ToFuProject/tofu#519]
## Context
Sometimes I need a quick and easy realistic configuration without structures, but to which I can add structures easily for testing.
But when all PFC structures are removed, there is an exception raised.

## Message Exception

> ---------------------------------------------------------------------------
> Exception                                 Traceback (most recent call last)
> <ipython-input-9-2cdcf2bfc5ba> in <module>
> ----> 1 config.remove_Struct(Cls="PFC", Name='DivLowITERV1')
> 
> ~/repositories/forked_tofu/tofu/tofu/geom/_core.py in remove_Struct(self, Cls, Name)
>    3431             del dx[k[1:]][Cls][Name]
>    3432 
> -> 3433         self._init(lStruct=lS, Lim=self.Lim, dextraprop=dx)
>    3434 
>    3435     def get_color(self):
> 
> ~/repositories/forked_tofu/tofu/tofu/geom/_core.py in _init(self, lStruct, Lim, dextraprop, **kwdargs)
>    2711         kwdextraprop = self._extract_kwdargs(locals(), largs)
>    2712         self._set_dStruct(**kwdStruct)
> -> 2713         self._set_dextraprop(**kwdextraprop)
>    2714         self._dynamicattr()
>    2715         self._dstrip["strip"] = 0
> 
> ~/repositories/forked_tofu/tofu/tofu/geom/_core.py in _set_dextraprop(self, dextraprop)
>    2727 
>    2728     def _set_dextraprop(self, dextraprop=None):
> -> 2729         dextraprop, dC = self._checkformat_inputs_dextraprop(dextraprop)
>    2730         self._dextraprop["lprop"] = sorted(list(dextraprop.keys()))
>    2731 
> 
> ~/repositories/forked_tofu/tofu/tofu/geom/_core.py in _checkformat_inputs_dextraprop(self, dextraprop)
>    2672         dC = {}
>    2673         for k in dextraprop.keys():
> -> 2674             dC[k] = self._checkformat_inputs_extraval(dextraprop[k], key=k)
>    2675         return dextraprop, dC
>    2676 
> 
> ~/repositories/forked_tofu/tofu/tofu/geom/_core.py in _checkformat_inputs_extraval(self, extraval, key, multi, size)
>    2623                 msg += "\n    expected : " + str(lk)
>    2624                 msg += "\n    received : " + str(sorted(extraval.keys()))
> -> 2625                 raise Exception(msg0 + msg)
>    2626             c = [isinstance(extraval[k], dict) for k in lk]
>    2627             if not all(c):
> 
> Exception: If an extra attribute is provided as a dict, it should have the same structure as self.dStruct !
> The value for visible has wrong keys !
>     expected : ['Ves']
>     received : ['PFC', 'Ves']

Minimal working example:

```
 import tofu as tf
config = tf.load_config("A1")
config.remove_Struct(Cls="PFC", Name='BaffleV0')
config.remove_Struct(Cls="PFC", Name='DivUpV1')
config.remove_Struct(Cls="PFC", Name='DivLowITERV1')
```

##  Feature requests
- I don't know if the `Name` is an id of the structures (eg. no two structures can have the same name), but if it is the case, is it necessary to provide the Class of the structure?
- Could there be a function `remove_all_PFC_structs()`? I might be the only one who needs it in which case nvm, but I find it useful to be able to strip a vessel of all PFCs

## Details

I have tried this with different versions of tofu

**Comment by Didou09** [comment]
OK, this should not be too hard to implement, I'll deal with it
