### ISSUE TITLE
Implement ideal planar crystal with slit option

### ISSUE THREAD

**Issue by dvezinet** [ToFuProject/tofu#754]

**Comment by cjperks7** [comment]
I've noticed when trying to call `diag.get_crystal_ideal_configuration()` when using a planar crystal with a slit, in `_class5_compute._ideal_configuration_check()` that if `gtype='planar'` then the only assumed available configuration is a pinhole:
<img width="370" alt="Screenshot 2023-05-04 at 2 12 44 PM" src="https://user-images.githubusercontent.com/71457911/236292413-fe70ad0f-c318-4229-a40d-59c929a6f777.png">

Further down, it seems having "aperture dimensions" as a slit is only available if `configuration== 'von hamos'`:
<img width="593" alt="Screenshot 2023-05-04 at 2 14 23 PM" src="https://user-images.githubusercontent.com/71457911/236292733-37ea39a8-3160-4fe6-99c7-99d72d23666d.png">
