### ISSUE TITLE
Cython dependency : check whether dependecy can be relaxed in pre-compiled installs

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#93]
If the user installs from a pre-compiled version (i.e.: conda or wheel), the cython dependency can probably be relaxed ?

Check if possible and check out standard / good practices in the community / other libraries.

Method : branch from devel with issue number

**Comment by flothesof** [comment]
After looking around, I believe the way the setup.py is written is common practice.
The Cython docs mention the same lines that the ones we're using (see [here](http://docs.cython.org/en/latest/src/quickstart/build.html)).
Another package, choldate, does something similar to us: see [here](https://github.com/modusdatascience/choldate/blob/master/setup.py).

**Comment by Didou09** [comment]
Thanks !

So we'll simply add a try / except statement at cython import time then, with an explicit warning message and test it out

**Comment by flothesof** [comment]
I think this issue can be closed, in the sense that there is nothing to fix as of right now.
We can consider reopening later if needed.

**Comment by Didou09** [comment]
Agreed
