### ISSUE TITLE
Is wavelength bspline required when defining emissivity data?

### ISSUE THREAD

**Issue by cjperks7** [ToFuProject/tofu#999]
Maybe I'm setting up my emissivity data wrong, but I'm getting the following error when running `coll.compute_diagnostic_signal`:
<img width="962" alt="Screenshot 2024-12-13 at 10 05 08 AM" src="https://github.com/user-attachments/assets/85978b21-58c2-44e4-b87a-5e949d41bcf7" />

The following code is stuff I ripping from `tofu_sparc` so things might have changed.

When I define my (R,Z) mesh and bsplines, I do:
<img width="513" alt="Screenshot 2024-12-13 at 10 06 20 AM" src="https://github.com/user-attachments/assets/0cc95441-ec76-4051-8d7b-b96c8d6f75fd" />

When I define my (wavelength) mesh, I do:
<img width="333" alt="Screenshot 2024-12-13 at 10 07 13 AM" src="https://github.com/user-attachments/assets/93d1feb0-5c7f-45f5-83c8-2dad17ab78f2" />

When I define my (emissivity) mesh, I do:
<img width="326" alt="Screenshot 2024-12-13 at 10 07 34 AM" src="https://github.com/user-attachments/assets/6b5a5860-a71a-47cb-99da-17a9a279233b" />

When I define my wavelength mesh, I had commented out making a bspline since it wasn't needed, but I guess now it is? What I'm guessing I should do to fix things is
1) replace my commented out wavelength bspline with:
```
coll.add_bsplines(
            key='nlamb_'+key_diag,
            deg=1
            )
```
to match how I did it with the (R,Z) mesh and to maintain the reference

2) replace the reference in the emissivity data to `ref=('m0_bs1','nlamb_'+key_diag+'_bs1')`

Does that sound right? What do you think?

**Comment by Didou09** [comment]
So yes, I remember I had started re-working that part and may have made spectral bsplines necessary without noticing.

I'd advise you basically un-comment the spectral mesh creation, and instead comment out the add_ref() and add_data().

```
coll.add_mesh_1d(
     key='mlamb_'+key_diag,
     knots=lamb*1e-10,
     deg=1,
    units='m',
)
```

Then just declare the spectral mesh as a reference for the emissivity
```
coll.add_data(
    key='emiss_'+key_diag,
    data=emiss2d_tmp_m0,
    ref=('m0_bs2', 'mlamb_bs1'),
    units='ph/s/m3/sr/m',
)
```

**Comment by cjperks7** [comment]
Sounds good! I'll test a low-resolution version and let you know if it works out

**Comment by cjperks7** [comment]
Seems like things are working now. Thank you very much!
